# Generated by Django 4.2.7 on 2025-11-08 02:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="County",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="County name", max_length=100)),
                (
                    "fips_code",
                    models.CharField(
                        blank=True,
                        help_text="5-digit FIPS code",
                        max_length=5,
                        null=True,
                        unique=True,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Counties",
                "ordering": ["state__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="LoanEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_address", models.TextField(blank=True)),
                (
                    "property_value",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("single_family", "Single Family"),
                            ("condo", "Condominium"),
                            ("townhouse", "Townhouse"),
                            ("multi_family", "Multi-Family"),
                        ],
                        max_length=20,
                    ),
                ),
                ("loan_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("down_payment", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Annual interest rate (e.g., 6.5)",
                        max_digits=5,
                    ),
                ),
                ("loan_term_years", models.IntegerField(default=30)),
                (
                    "loan_type",
                    models.CharField(
                        choices=[
                            ("conventional", "Conventional"),
                            ("fha", "FHA"),
                            ("va", "VA"),
                            ("usda", "USDA"),
                        ],
                        max_length=20,
                    ),
                ),
                ("first_time_homebuyer", models.BooleanField(default=False)),
                ("closing_date", models.DateField()),
                (
                    "calculation_results",
                    models.JSONField(
                        help_text="Complete calculation breakdown including all sections"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_saved",
                    models.BooleanField(
                        default=False, help_text="User chose to save this estimate"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="User-provided name for this estimate",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Municipality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "millage_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        help_text="Additional municipal tax rate",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "zip_codes",
                    models.JSONField(
                        default=list, help_text="List of zip codes in this municipality"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Municipalities",
                "ordering": ["county", "name"],
            },
        ),
        migrations.CreateModel(
            name="ScraperLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("partial", "Partial Success"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_time",
                    models.FloatField(
                        blank=True, help_text="Time in seconds", null=True
                    ),
                ),
                ("data_completeness", models.IntegerField(blank=True, null=True)),
                ("confidence_score", models.IntegerField(blank=True, null=True)),
                ("sources_found", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("llm_provider", models.CharField(blank=True, max_length=50)),
                ("llm_model", models.CharField(blank=True, max_length=100)),
                ("tokens_used", models.IntegerField(blank=True, null=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("api", "API Request"),
                            ("scheduled", "Scheduled"),
                            ("stale_data", "Stale Data Refresh"),
                        ],
                        default="api",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Two-letter state code (e.g., 'MD')",
                        max_length=2,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Full state name", max_length=100)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annual_income",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "credit_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(300),
                            django.core.validators.MaxValueValidator(850),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_county",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.county",
                    ),
                ),
                (
                    "default_state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.state",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaxData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                (
                    "is_current",
                    models.BooleanField(
                        default=True, help_text="Is this the current version?"
                    ),
                ),
                (
                    "data_completeness",
                    models.IntegerField(
                        help_text="Percentage of required fields populated (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "scraper_confidence",
                    models.IntegerField(
                        help_text="LLM confidence score (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text="Complete tax data structure including rates, fees, and calculations"
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        help_text="Date when these rates became effective"
                    ),
                ),
                ("last_verified", models.DateTimeField(auto_now=True)),
                (
                    "sources",
                    models.JSONField(default=list, help_text="List of source URLs"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or caveats"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_data",
                        to="api.county",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_data",
                        to="api.state",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tax Data",
                "ordering": ["-is_current", "-version", "-last_verified"],
            },
        ),
        migrations.AddIndex(
            model_name="state",
            index=models.Index(fields=["code"], name="api_state_code_ba9476_idx"),
        ),
        migrations.AddIndex(
            model_name="state",
            index=models.Index(fields=["active"], name="api_state_active_12a88e_idx"),
        ),
        migrations.AddField(
            model_name="scraperlog",
            name="county",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scraper_logs",
                to="api.county",
            ),
        ),
        migrations.AddField(
            model_name="scraperlog",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scraper_logs",
                to="api.state",
            ),
        ),
        migrations.AddField(
            model_name="scraperlog",
            name="triggered_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who triggered this scrape (if manual)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="municipality",
            name="county",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="municipalities",
                to="api.county",
            ),
        ),
        migrations.AddField(
            model_name="loanestimate",
            name="county",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loan_estimates",
                to="api.county",
            ),
        ),
        migrations.AddField(
            model_name="loanestimate",
            name="tax_data",
            field=models.ForeignKey(
                help_text="Version of tax data used in this calculation",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loan_estimates",
                to="api.taxdata",
            ),
        ),
        migrations.AddField(
            model_name="loanestimate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan_estimates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="county",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="counties",
                to="api.state",
            ),
        ),
        migrations.AddIndex(
            model_name="taxdata",
            index=models.Index(
                fields=["state", "county", "is_current"],
                name="api_taxdata_state_i_79dcbd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taxdata",
            index=models.Index(
                fields=["last_verified"], name="api_taxdata_last_ve_9b2c7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taxdata",
            index=models.Index(
                fields=["data_completeness"], name="api_taxdata_data_co_e9fe11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taxdata",
            index=models.Index(
                fields=["effective_date"], name="api_taxdata_effecti_0afaf2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taxdata",
            unique_together={("state", "county", "version")},
        ),
        migrations.AddIndex(
            model_name="scraperlog",
            index=models.Index(
                fields=["state", "county", "-started_at"],
                name="api_scraper_state_i_9f5d1f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scraperlog",
            index=models.Index(fields=["status"], name="api_scraper_status_660bc7_idx"),
        ),
        migrations.AddIndex(
            model_name="scraperlog",
            index=models.Index(
                fields=["-started_at"], name="api_scraper_started_52edf6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="municipality",
            unique_together={("county", "name")},
        ),
        migrations.AddIndex(
            model_name="loanestimate",
            index=models.Index(
                fields=["user", "-created_at"], name="api_loanest_user_id_28d122_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loanestimate",
            index=models.Index(
                fields=["county"], name="api_loanest_county__a2170a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loanestimate",
            index=models.Index(
                fields=["is_saved"], name="api_loanest_is_save_9d28c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="county",
            index=models.Index(
                fields=["state", "name"], name="api_county_state_i_2cf2f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="county",
            index=models.Index(
                fields=["fips_code"], name="api_county_fips_co_e794de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="county",
            index=models.Index(fields=["active"], name="api_county_active_51a8e7_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="county",
            unique_together={("state", "name")},
        ),
    ]
