# Generated by Django 4.2.7 on 2025-11-09 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanestimate",
            name="admin_feedback",
            field=models.TextField(
                blank=True,
                help_text="Admin feedback for corrections or rejection reason",
            ),
        ),
        migrations.AddField(
            model_name="loanestimate",
            name="correction_count",
            field=models.IntegerField(
                default=0,
                help_text="Number of times application was sent back for corrections",
            ),
        ),
        migrations.AddField(
            model_name="loanestimate",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True, help_text="When admin reviewed application", null=True
            ),
        ),
        migrations.AddField(
            model_name="loanestimate",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who reviewed this application",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_loan_estimates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loanestimate",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("under_review", "Under Review"),
                    ("needs_correction", "Needs Correction"),
                    ("resubmitted", "Resubmitted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                help_text="Current application status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="loanestimate",
            name="submitted_at",
            field=models.DateTimeField(
                blank=True, help_text="When user submitted application", null=True
            ),
        ),
        migrations.AddField(
            model_name="taxdata",
            name="data_version",
            field=models.CharField(
                default="1.0",
                help_text="Schema version (e.g., '2.0' for enhanced schema)",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="loanestimate",
            index=models.Index(
                fields=["status", "-created_at"], name="api_loanest_status_792948_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loanestimate",
            index=models.Index(
                fields=["submitted_at"], name="api_loanest_submitt_f28e1b_idx"
            ),
        ),
    ]
