# Generated by Django 4.2.7 on 2025-11-09 23:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0002_loanestimate_admin_feedback_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bureau",
                    models.CharField(
                        choices=[
                            ("equifax", "Equifax"),
                            ("experian", "Experian"),
                            ("transunion", "TransUnion"),
                            ("merged", "Merged Report"),
                        ],
                        default="merged",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Pull"),
                            ("pulled", "Successfully Pulled"),
                            ("error", "Error"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "equifax_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(300),
                            django.core.validators.MaxValueValidator(850),
                        ],
                    ),
                ),
                (
                    "experian_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(300),
                            django.core.validators.MaxValueValidator(850),
                        ],
                    ),
                ),
                (
                    "transunion_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(300),
                            django.core.validators.MaxValueValidator(850),
                        ],
                    ),
                ),
                ("report_date", models.DateTimeField(auto_now_add=True)),
                (
                    "report_id",
                    models.CharField(
                        blank=True,
                        help_text="External credit bureau reference ID",
                        max_length=100,
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw credit report data from bureau API",
                    ),
                ),
                ("total_tradelines", models.IntegerField(default=0)),
                ("total_inquiries", models.IntegerField(default=0)),
                (
                    "total_monthly_debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Sum of all monthly debt payments",
                        max_digits=10,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Credit reports expire after 120 days",
                        null=True,
                    ),
                ),
                (
                    "loan_estimate",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated loan application",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_reports",
                        to="api.loanestimate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Borrower whose credit was pulled",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="Tradeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("mortgage", "Mortgage"),
                            ("auto", "Auto Loan"),
                            ("student", "Student Loan"),
                            ("credit_card", "Credit Card"),
                            ("personal", "Personal Loan"),
                            ("installment", "Installment Loan"),
                            ("collection", "Collection Account"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("creditor_name", models.CharField(max_length=200)),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        help_text="Last 4 digits only for security",
                        max_length=50,
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=12
                    ),
                ),
                (
                    "monthly_payment",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=10
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="For revolving accounts",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("paid", "Paid Off"),
                            ("charge_off", "Charge Off"),
                            ("collection", "In Collection"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("opened_date", models.DateField(blank=True, null=True)),
                ("last_payment_date", models.DateField(blank=True, null=True)),
                ("days_past_due", models.IntegerField(default=0)),
                (
                    "confirmation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("confirmed", "Confirmed"),
                            ("disputed", "Disputed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("dispute_reason", models.TextField(blank=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "credit_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tradelines",
                        to="api.creditreport",
                    ),
                ),
            ],
            options={
                "ordering": ["account_type", "-current_balance"],
            },
        ),
        migrations.CreateModel(
            name="DocTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("dispute_tradeline", "Dispute Tradeline"),
                            ("verify_tradeline", "Verify Tradeline"),
                            ("upload_document", "Upload Supporting Document"),
                            ("provide_explanation", "Provide Explanation"),
                            ("verify_income", "Verify Income"),
                            ("verify_assets", "Verify Assets"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(help_text="Instructions for borrower"),
                ),
                ("borrower_notes", models.TextField(blank=True)),
                (
                    "uploaded_documents",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of document IDs uploaded for this task",
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "loan_estimate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doc_tasks",
                        to="api.loanestimate",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_doc_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tradeline",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated tradeline if task is debt-related",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doc_tasks",
                        to="api.tradeline",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doc_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["status", "due_date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="creditreport",
            index=models.Index(
                fields=["user", "-report_date"], name="api_creditr_user_id_c90d33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creditreport",
            index=models.Index(
                fields=["loan_estimate"], name="api_creditr_loan_es_8b1e2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creditreport",
            index=models.Index(fields=["status"], name="api_creditr_status_9c6b24_idx"),
        ),
        migrations.AddIndex(
            model_name="creditreport",
            index=models.Index(
                fields=["-report_date"], name="api_creditr_report__ef7425_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tradeline",
            index=models.Index(
                fields=["credit_report", "confirmation_status"],
                name="api_tradeli_credit__b70c92_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tradeline",
            index=models.Index(
                fields=["account_type"], name="api_tradeli_account_51e9f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tradeline",
            index=models.Index(
                fields=["confirmation_status"],
                name="api_tradeli_confirm_3a6c94_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="doctask",
            index=models.Index(
                fields=["user", "status"], name="api_doctask_user_id_e8f1a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctask",
            index=models.Index(
                fields=["loan_estimate", "status"],
                name="api_doctask_loan_es_4c9d37_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="doctask",
            index=models.Index(
                fields=["tradeline"], name="api_doctask_tradeli_b89f14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctask",
            index=models.Index(
                fields=["status", "due_date"], name="api_doctask_status_6e5a09_idx"
            ),
        ),
    ]
