# Generated by Django 4.2.7 on 2025-11-10 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0003_add_credit_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("credit_consent", "Credit Consent Given"),
                            ("credit_pull", "Credit Report Pulled"),
                            ("pii_access", "PII Data Accessed"),
                            ("document_view", "Document Viewed"),
                            ("application_submit", "Application Submitted"),
                            ("application_approve", "Application Approved"),
                            ("application_reject", "Application Rejected"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("borrower_name", models.CharField(blank=True, max_length=200)),
                (
                    "ssn_last_four",
                    models.CharField(
                        blank=True,
                        help_text="Last 4 digits of SSN (masked for security)",
                        max_length=4,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context data for the event",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.RenameIndex(
            model_name="creditreport",
            new_name="api_creditr_user_id_c1185b_idx",
            old_name="api_creditr_user_id_c90d33_idx",
        ),
        migrations.RenameIndex(
            model_name="creditreport",
            new_name="api_creditr_loan_es_bee656_idx",
            old_name="api_creditr_loan_es_8b1e2f_idx",
        ),
        migrations.RenameIndex(
            model_name="creditreport",
            new_name="api_creditr_status_906ee8_idx",
            old_name="api_creditr_status_9c6b24_idx",
        ),
        migrations.RenameIndex(
            model_name="creditreport",
            new_name="api_creditr_report__f2c2ec_idx",
            old_name="api_creditr_report__ef7425_idx",
        ),
        migrations.RenameIndex(
            model_name="doctask",
            new_name="api_doctask_user_id_9790da_idx",
            old_name="api_doctask_user_id_e8f1a2_idx",
        ),
        migrations.RenameIndex(
            model_name="doctask",
            new_name="api_doctask_loan_es_5c2efb_idx",
            old_name="api_doctask_loan_es_4c9d37_idx",
        ),
        migrations.RenameIndex(
            model_name="doctask",
            new_name="api_doctask_tradeli_186268_idx",
            old_name="api_doctask_tradeli_b89f14_idx",
        ),
        migrations.RenameIndex(
            model_name="doctask",
            new_name="api_doctask_status_957932_idx",
            old_name="api_doctask_status_6e5a09_idx",
        ),
        migrations.RenameIndex(
            model_name="tradeline",
            new_name="api_tradeli_credit__038659_idx",
            old_name="api_tradeli_credit__b70c92_idx",
        ),
        migrations.RenameIndex(
            model_name="tradeline",
            new_name="api_tradeli_account_da1fcc_idx",
            old_name="api_tradeli_account_51e9f8_idx",
        ),
        migrations.RenameIndex(
            model_name="tradeline",
            new_name="api_tradeli_confirm_c4a09a_idx",
            old_name="api_tradeli_confirm_3a6c94_idx",
        ),
        migrations.AddField(
            model_name="tradeline",
            name="has_less_than_10_payments",
            field=models.BooleanField(
                default=False,
                help_text="Account has fewer than 10 reported payments (new account)",
            ),
        ),
        migrations.AddField(
            model_name="tradeline",
            name="is_cosigned",
            field=models.BooleanField(
                default=False, help_text="Account has a co-signer"
            ),
        ),
        migrations.AddField(
            model_name="tradeline",
            name="is_deferred",
            field=models.BooleanField(
                default=False,
                help_text="Account is in deferment (common for student loans)",
            ),
        ),
        migrations.AddField(
            model_name="tradeline",
            name="is_disputed",
            field=models.BooleanField(
                default=False,
                help_text="Borrower is disputing this tradeline with bureau",
            ),
        ),
        migrations.AddField(
            model_name="tradeline",
            name="is_ibr",
            field=models.BooleanField(
                default=False, help_text="Income-Based Repayment plan (student loans)"
            ),
        ),
        migrations.AddField(
            model_name="tradeline",
            name="lates_30_count_24mo",
            field=models.IntegerField(
                default=0, help_text="Count of 30+ day late payments in last 24 months"
            ),
        ),
        migrations.AddField(
            model_name="tradeline",
            name="lates_30_count_36mo",
            field=models.IntegerField(
                default=0, help_text="Count of 30+ day late payments in last 36 months"
            ),
        ),
        migrations.AddField(
            model_name="tradeline",
            name="lates_60_count_24mo",
            field=models.IntegerField(
                default=0, help_text="Count of 60+ day late payments in last 24 months"
            ),
        ),
        migrations.AddField(
            model_name="tradeline",
            name="lates_60_count_36mo",
            field=models.IntegerField(
                default=0, help_text="Count of 60+ day late payments in last 36 months"
            ),
        ),
        migrations.AddField(
            model_name="tradeline",
            name="lates_90_count_24mo",
            field=models.IntegerField(
                default=0, help_text="Count of 90+ day late payments in last 24 months"
            ),
        ),
        migrations.AddField(
            model_name="tradeline",
            name="lates_90_count_36mo",
            field=models.IntegerField(
                default=0, help_text="Count of 90+ day late payments in last 36 months"
            ),
        ),
        migrations.AddField(
            model_name="tradeline",
            name="months_reviewed",
            field=models.IntegerField(
                blank=True,
                help_text="Number of months of payment history available",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tradeline",
            name="payment_count",
            field=models.IntegerField(
                default=0, help_text="Total number of payments reported"
            ),
        ),
        migrations.AddField(
            model_name="tradeline",
            name="remarks",
            field=models.TextField(
                blank=True,
                help_text="Creditor remarks or bureau notes (e.g., 'Account closed by consumer')",
            ),
        ),
        migrations.AddIndex(
            model_name="tradeline",
            index=models.Index(
                fields=["is_deferred", "is_ibr"], name="api_tradeli_is_defe_899a38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tradeline",
            index=models.Index(
                fields=["has_less_than_10_payments"],
                name="api_tradeli_has_les_530140_idx",
            ),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="loan_estimate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_events",
                to="api.loanestimate",
            ),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who triggered the event",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["event_type", "-timestamp"],
                name="api_auditev_event_t_a3b3a1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["user", "-timestamp"], name="api_auditev_user_id_005a94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["ssn_last_four", "-timestamp"],
                name="api_auditev_ssn_las_b08a75_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["-timestamp"], name="api_auditev_timesta_cc23a0_idx"
            ),
        ),
    ]
