# Generated by Django 4.2.7 on 2025-11-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_userprofile_mortgage_statuses"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditreport",
            name="ssn_encrypted",
            field=models.TextField(
                blank=True,
                help_text="Encrypted SSN for borrower identity verification (AES-128)",
            ),
        ),
    ]
