# Generated by Django 4.2.7 on 2025-11-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_add_ssn_encryption_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("credit_consent", "Credit Consent Given"),
                    ("credit_pull", "Credit Report Pulled"),
                    ("pii_access", "PII Data Accessed"),
                    ("document_view", "Document Viewed"),
                    ("document_upload", "Document Uploaded"),
                    ("document_scan", "Document Virus Scanned"),
                    ("document_ocr", "Document OCR Processed"),
                    ("document_rejected", "Document Rejected"),
                    ("application_submit", "Application Submitted"),
                    ("application_approve", "Application Approved"),
                    ("application_reject", "Application Rejected"),
                ],
                max_length=50,
            ),
        ),
    ]
