# Generated by Django 4.2.7 on 2025-11-10 06:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0007_alter_auditevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("credit_consent", "Credit Consent Given"),
                    ("credit_pull", "Credit Report Pulled"),
                    ("pii_access", "PII Data Accessed"),
                    ("document_view", "Document Viewed"),
                    ("document_upload", "Document Uploaded"),
                    ("document_scan", "Document Virus Scanned"),
                    ("document_ocr", "Document OCR Processed"),
                    ("document_rejected", "Document Rejected"),
                    ("application_submit", "Application Submitted"),
                    ("application_approve", "Application Approved"),
                    ("application_reject", "Application Rejected"),
                    ("preapproval_create", "Pre-Approval Created"),
                    ("preapproval_submit", "Pre-Approval Submitted"),
                    ("preapproval_approve", "Pre-Approval Approved"),
                    ("preapproval_deny", "Pre-Approval Denied"),
                    ("preapproval_letter_generate", "Pre-Approval Letter Generated"),
                    ("preapproval_letter_publish", "Pre-Approval Letter Published"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="PricingScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loan_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "property_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "credit_score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(300),
                            django.core.validators.MaxValueValidator(850),
                        ]
                    ),
                ),
                (
                    "loan_type",
                    models.CharField(
                        choices=[
                            ("conventional", "Conventional"),
                            ("fha", "FHA"),
                            ("va", "VA"),
                            ("usda", "USDA"),
                        ],
                        default="conventional",
                        max_length=20,
                    ),
                ),
                (
                    "occupancy",
                    models.CharField(
                        choices=[
                            ("primary", "Primary Residence"),
                            ("secondary", "Secondary Home"),
                            ("investment", "Investment Property"),
                        ],
                        default="primary",
                        max_length=20,
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("single_family", "Single Family"),
                            ("condo", "Condominium"),
                            ("townhouse", "Townhouse"),
                            ("multi_family", "Multi-Family"),
                        ],
                        default="single_family",
                        max_length=20,
                    ),
                ),
                (
                    "loan_term_months",
                    models.IntegerField(
                        default=360,
                        help_text="Loan term in months (360 = 30 years, 180 = 15 years)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "loan_purpose",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("refinance", "Refinance"),
                            ("cash_out", "Cash-Out Refinance"),
                        ],
                        default="purchase",
                        max_length=20,
                    ),
                ),
                (
                    "documentation_type",
                    models.CharField(
                        choices=[
                            ("full_doc", "Full Documentation"),
                            ("alt_doc", "Alternative Documentation"),
                            ("no_doc", "No Documentation"),
                        ],
                        default="full_doc",
                        max_length=20,
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=2)),
                ("county", models.CharField(blank=True, max_length=100)),
                ("zip_code", models.CharField(blank=True, max_length=10)),
                (
                    "debt_to_income_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "pricing_options",
                    models.JSONField(
                        default=list,
                        help_text="List of pricing options from investor API",
                    ),
                ),
                (
                    "selected_option_index",
                    models.IntegerField(
                        blank=True,
                        help_text="Index of selected pricing option in pricing_options array",
                        null=True,
                    ),
                ),
                (
                    "pricing_provider",
                    models.CharField(
                        default="MockInvestor",
                        help_text="Name of pricing adapter/provider",
                        max_length=100,
                    ),
                ),
                (
                    "pricing_timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When pricing was retrieved"
                    ),
                ),
                (
                    "pricing_request_id",
                    models.CharField(
                        blank=True,
                        help_text="External pricing request ID for audit trail",
                        max_length=100,
                    ),
                ),
                (
                    "execution_time_ms",
                    models.IntegerField(
                        default=0,
                        help_text="Pricing API execution time in milliseconds",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="User-provided scenario name",
                        max_length=200,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="User notes about this scenario"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "loan_estimate",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional reference to loan estimate",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pricing_scenarios",
                        to="api.loanestimate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created this scenario",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_scenarios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PricingAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pricing_provider", models.CharField(max_length=100)),
                (
                    "request_parameters",
                    models.JSONField(
                        help_text="Full request parameters sent to pricing API"
                    ),
                ),
                (
                    "response_data",
                    models.JSONField(
                        blank=True,
                        help_text="Full response from pricing API",
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("execution_time_ms", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("error", "Error"),
                            ("timeout", "Timeout"),
                            ("validation_error", "Validation Error"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "pricing_scenario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="api.pricingscenario",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pricing_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PreApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borrower_name", models.CharField(max_length=200)),
                ("co_borrower_name", models.CharField(blank=True, max_length=200)),
                ("borrower_email", models.EmailField(blank=True, max_length=254)),
                ("borrower_phone", models.CharField(blank=True, max_length=20)),
                (
                    "annual_income",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "monthly_income",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_assets",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_liabilities",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "credit_score_estimate",
                    models.IntegerField(
                        help_text="Estimated credit score",
                        validators=[
                            django.core.validators.MinValueValidator(300),
                            django.core.validators.MaxValueValidator(850),
                        ],
                    ),
                ),
                (
                    "front_end_dti",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Front-end debt-to-income ratio",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "back_end_dti",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Back-end debt-to-income ratio",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("property_address", models.TextField(blank=True)),
                (
                    "property_value_estimate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "down_payment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "loan_type",
                    models.CharField(
                        choices=[
                            ("conventional", "Conventional"),
                            ("fha", "FHA"),
                            ("va", "VA"),
                            ("usda", "USDA"),
                        ],
                        default="conventional",
                        max_length=20,
                    ),
                ),
                (
                    "max_loan_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum approved loan amount",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum approved purchase price",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "estimated_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Estimated interest rate",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(help_text="Date when pre-approval expires"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "letter_generated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the official letter was generated",
                        null=True,
                    ),
                ),
                (
                    "letter_published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the letter was published/sent",
                        null=True,
                    ),
                ),
                (
                    "letter_pdf_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to generated PDF letter",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes (not shown on letter)"
                    ),
                ),
                (
                    "conditions",
                    models.TextField(
                        blank=True, help_text="Special conditions or requirements"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who approved this pre-approval",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_pre_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan_estimate",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional reference to existing loan estimate",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pre_approvals",
                        to="api.loanestimate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Loan officer or admin who created this pre-approval",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pre_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="pricingscenario",
            index=models.Index(
                fields=["user", "-created_at"], name="api_pricing_user_id_e8b16e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricingscenario",
            index=models.Index(
                fields=["loan_estimate"], name="api_pricing_loan_es_279201_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricingscenario",
            index=models.Index(
                fields=["pricing_provider", "-created_at"],
                name="api_pricing_pricing_003434_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricingscenario",
            index=models.Index(
                fields=["-pricing_timestamp"], name="api_pricing_pricing_333ab0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricingauditlog",
            index=models.Index(
                fields=["pricing_provider", "-timestamp"],
                name="api_pricing_pricing_0273c0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricingauditlog",
            index=models.Index(
                fields=["user", "-timestamp"], name="api_pricing_user_id_967523_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricingauditlog",
            index=models.Index(
                fields=["status", "-timestamp"], name="api_pricing_status_7f7443_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricingauditlog",
            index=models.Index(
                fields=["-timestamp"], name="api_pricing_timesta_49894b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="preapproval",
            index=models.Index(
                fields=["user", "-created_at"], name="api_preappr_user_id_513bec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="preapproval",
            index=models.Index(
                fields=["status", "-created_at"], name="api_preappr_status_eefd53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="preapproval",
            index=models.Index(
                fields=["expiration_date"], name="api_preappr_expirat_f6f5bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="preapproval",
            index=models.Index(
                fields=["borrower_email"], name="api_preappr_borrowe_959e22_idx"
            ),
        ),
    ]
