# Generated by Django 4.2.7 on 2025-11-10 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_add_fee_calculation_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Tenant name (e.g., 'ABC Mortgage Co.')",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier", max_length=100, unique=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Tenant is active and can be used"
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to tenant logo image (for reports and UI)",
                        max_length=500,
                    ),
                ),
                (
                    "logo_base64",
                    models.TextField(
                        blank=True,
                        help_text="Base64-encoded logo for embedded PDF reports",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#667eea",
                        help_text="Primary brand color (hex format)",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Color must be a valid hex code (e.g., #667eea)",
                                regex="^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$",
                            )
                        ],
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#10b981",
                        help_text="Secondary brand color (hex format)",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Color must be a valid hex code (e.g., #667eea)",
                                regex="^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$",
                            )
                        ],
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#764ba2",
                        help_text="Accent color for highlights (hex format)",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Color must be a valid hex code (e.g., #667eea)",
                                regex="^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$",
                            )
                        ],
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Tenant contact email (shown on reports)",
                        max_length=254,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Tenant contact phone (shown on reports)",
                        max_length=20,
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, help_text="Tenant website URL"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RenameIndex(
            model_name="feecalculation",
            new_name="api_feecalc_user_id_347a22_idx",
            old_name="api_feecalc_user_id_calc_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="feecalculation",
            new_name="api_feecalc_loan_es_c97024_idx",
            old_name="api_feecalc_loan_est_id_calc_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="feecalculation",
            new_name="api_feecalc_pricing_2e976f_idx",
            old_name="api_feecalc_pricing_scen_id_calc_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="feecalculation",
            new_name="api_feecalc_determi_24d759_idx",
            old_name="api_feecalc_det_hash_idx",
        ),
        migrations.RenameIndex(
            model_name="feecalculation",
            new_name="api_feecalc_jurisdi_2d4abc_idx",
            old_name="api_feecalc_jurisdiction_calc_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="feecalculation",
            new_name="api_feecalc_calcula_f82190_idx",
            old_name="api_feecalc_calc_ts_idx",
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["slug"], name="api_tenant_slug_51546e_idx"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(
                fields=["is_active"], name="api_tenant_is_acti_2e0e68_idx"
            ),
        ),
    ]
