# Generated by Django 4.2.7 on 2025-11-10 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS")], max_length=10
                    ),
                ),
                (
                    "milestone",
                    models.CharField(
                        choices=[
                            ("application_submitted", "Application Submitted"),
                            ("application_under_review", "Application Under Review"),
                            (
                                "application_needs_correction",
                                "Application Needs Correction",
                            ),
                            ("application_approved", "Application Approved"),
                            ("application_rejected", "Application Rejected"),
                            ("credit_report_pulled", "Credit Report Pulled"),
                            ("preapproval_submitted", "Pre-Approval Submitted"),
                            ("preapproval_approved", "Pre-Approval Approved"),
                            ("preapproval_denied", "Pre-Approval Denied"),
                            (
                                "preapproval_letter_generated",
                                "Pre-Approval Letter Generated",
                            ),
                            ("document_processed", "Document Processed"),
                            ("welcome", "Welcome Email"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                            ("delivered", "Delivered"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("recipient_email", models.EmailField(blank=True, max_length=254)),
                ("recipient_phone", models.CharField(blank=True, max_length=20)),
                ("subject", models.CharField(blank=True, max_length=200)),
                (
                    "message_preview",
                    models.CharField(
                        help_text="First 200 chars of message for audit trail",
                        max_length=200,
                    ),
                ),
                ("loan_estimate_id", models.IntegerField(blank=True, null=True)),
                ("preapproval_id", models.IntegerField(blank=True, null=True)),
                ("document_id", models.IntegerField(blank=True, null=True)),
                (
                    "provider",
                    models.CharField(
                        help_text="Email/SMS provider used (e.g., 'console', 'sendgrid', 'twilio')",
                        max_length=50,
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True,
                        help_text="External provider's message ID for tracking",
                        max_length=200,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="notificatio_user_id_57d53d_idx",
                    ),
                    models.Index(
                        fields=["milestone", "-created_at"],
                        name="notificatio_milesto_563c3a_idx",
                    ),
                    models.Index(
                        fields=["status", "retry_count"],
                        name="notificatio_status_25b332_idx",
                    ),
                    models.Index(
                        fields=["provider_message_id"],
                        name="notificatio_provide_9833c3_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="notificatio_created_651c44_idx"
                    ),
                ],
            },
        ),
    ]
