# Generated by Django 4.2.7 on 2025-11-08 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("pay_stub", "Pay Stub"),
                            ("w2", "W-2 Form"),
                            ("bank_statement", "Bank Statement"),
                            ("tax_return", "Tax Return"),
                            ("purchase_agreement", "Purchase Agreement"),
                            ("insurance", "Insurance Declaration"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file", models.FileField(upload_to="documents/%Y/%m/%d/")),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.IntegerField(help_text="File size in bytes")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("ocr_text", models.TextField(blank=True, help_text="Raw OCR output")),
                (
                    "extracted_data",
                    models.JSONField(
                        blank=True,
                        help_text="Structured data extracted by LLM",
                        null=True,
                    ),
                ),
                (
                    "extraction_confidence",
                    models.IntegerField(
                        blank=True, help_text="Confidence score 0-100", null=True
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
