# Generated by Django 4.2.7 on 2025-11-10 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_auditevent_event_type"),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentupload",
            name="detected_mime_type",
            field=models.CharField(
                blank=True, help_text="MIME type detected during upload", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="documentupload",
            name="doc_task",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated document task this upload fulfills",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="document_uploads",
                to="api.doctask",
            ),
        ),
        migrations.AddField(
            model_name="documentupload",
            name="loan_estimate",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated loan application",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supporting_documents",
                to="api.loanestimate",
            ),
        ),
        migrations.AddField(
            model_name="documentupload",
            name="scanned_at",
            field=models.DateTimeField(
                blank=True, help_text="When virus scan completed", null=True
            ),
        ),
        migrations.AddField(
            model_name="documentupload",
            name="virus_scan_passed",
            field=models.BooleanField(
                blank=True,
                help_text="True if virus scan passed, False if failed, None if not scanned",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="documentupload",
            name="virus_scan_result",
            field=models.JSONField(
                blank=True, help_text="Full virus scan result details", null=True
            ),
        ),
        migrations.AlterField(
            model_name="documentupload",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("scanning", "Virus Scanning"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("rejected", "Rejected (Security)"),
                ],
                default="uploaded",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="documentupload",
            index=models.Index(
                fields=["user", "-uploaded_at"], name="documents_d_user_id_23ef24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentupload",
            index=models.Index(
                fields=["doc_task"], name="documents_d_doc_tas_f545d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentupload",
            index=models.Index(
                fields=["loan_estimate"], name="documents_d_loan_es_620903_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentupload",
            index=models.Index(
                fields=["status", "-uploaded_at"], name="documents_d_status_fc78d9_idx"
            ),
        ),
    ]
